[workspace]
resolver = "2"
members = ["es-init", "es-rollout", "es-update"]

[workspace.dependencies]
inferlet = { path = "../../../rust/inferlet" }
inferlet-macros = { path = "../../../rust/inferlet-macros" }
[profile.release]
lto = true
