[package]
name = "text-completion"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
inferlet = { path = "../../sdk/rust/inferlet" }
inferlet-macros = { path = "../../sdk/rust/inferlet-macros" }

[profile.release]
lto = true
