[workspace]
resolver = "2"
members = ["brle", "brle-bindings", "chat", "chat-bindings", "dummy", "dummy-bindings", "environment", "environment-bindings", "context", "context-bindings", "context-pld", "model", "model-bindings", "queue", "queue-bindings", "run-bindings"]

[workspace.dependencies]
wit-bindgen = "0.48.0"

[profile.release]
lto = true
