[workspace]
members = ["crates/pycrust-ffi"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
pyo3 = { version = "0.23", features = ["auto-initialize"] }
rmp-serde = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
tokio = { version = "1.49", features = ["full"] }
