[package]
name = "inferlib-queue"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "inferlib_queue"

[dependencies]
wit-bindgen = { workspace = true }
wstd = "0.5.6"
wasip2 = "1.0.1"
