[package]
name = "es-init"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
inferlet = { path = "../../../../rust/inferlet" }
inferlet-macros = { path = "../../../../rust/inferlet-macros" }
futures = "0.3.31"
pico-args = "0.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"