[project]
name = "flashinfer-fuesd-moe-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flashinfer-python>=0.5.3",
    "torch>=2.9.1",
]
