[workspace]
resolver = "2"
members = [
    "version",
    "greet",
    "greet-lib",
    "runtime-instrument-lib",
    "echo",
]

[workspace.dependencies]
wit-bindgen = "0.48.0"
inferlet = { path = "../inferlet" }
inferlet-macros = { path = "../inferlet-macros" }
[profile.release]
lto = true
