[workspace]
resolver = "2"
members = ["text-completion", "text-completion-inferlib"]

[workspace.dependencies]
wit-bindgen = "0.48.0"
inferlet = { path = "../inferlet" }
inferlet-macros = { path = "../inferlet-macros" }
[profile.release]
lto = true
