[workspace]
resolver = "2"
members = [
    "prefix-caching",
    "text-completion",
    "windowed-attention",
]

[workspace.dependencies]
inferlet = { path = "../inferlet" }
inferlet-macros = { path = "../inferlet-macros" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[profile.release]
lto = true
