[package]
name = "zyma98/text-completion-inferlib"
version = "0.1.0"
dependencies = [
    "zyma98/inferlib-chat@0.1.0",
    "zyma98/inferlib-environment@0.1.0",
    "zyma98/inferlib-model@0.1.0",
    "zyma98/inferlib-context@0.1.0",
]

[engine]
min_version = "^1.0.0"
